# -*- coding: utf-8 -*-
"""Task_2_AI/ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10u9zzCz_qY9coNmD6j_ryEmIPE6G2EEj
"""

!pip install yfinance

#import libraries

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Apple stock data
stock = yf.download("AAPL", period="2y", auto_adjust=True)

# First 5 rows
stock.head()

# Predict next day's close price
stock["Next_Close"] = stock["Close"].shift(-1)

# Remove empty row
stock = stock.dropna()

# Features
X = stock[["Open", "High", "Low", "Volume"]]

# Target
y = stock["Next_Close"]

print(X.shape)
print(y.shape)

#Train-Test Split

split = int(len(X) * 0.8)

X_train = X[:split]
X_test = X[split:]

y_train = y[:split]
y_test = y[split:]

#Train Model

model = LinearRegression()

model.fit(X_train, y_train)

print("Model Training Complete")

#Make Predictions

predictions = model.predict(X_test)

print(predictions[:5])

#Evaluate Model

mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("MAE:", mae)
print("MSE:", mse)
print("R2 Score:", r2)

#Plot Actual vs Predicted Prices

plt.figure(figsize=(12,6))

plt.plot(y_test.values, label="Actual Price")
plt.plot(predictions, label="Predicted Price")

plt.title("Actual vs Predicted Closing Prices")
plt.xlabel("Days")
plt.ylabel("Price")
plt.legend()
plt.grid(True)

plt.show()