# -*- coding: utf-8 -*-
"""Task_1_AI/ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zP5OW57b76uZbPLSA4ILvp6u30jzAc0S

Task 1: Exploring and Visualizing the Iris Dataset

Objective:
To learn how to load, inspect, analyze, and visualize a dataset using Pandas, Matplotlib, and Seaborn.
"""

# Commented out IPython magic to ensure Python compatibility.
# Import required libraries

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Display plots inside notebook
# %matplotlib inline

# Load Iris Dataset

iris = sns.load_dataset('iris')

print("Dataset Loaded Successfully!")

# Shape of dataset

print("Shape of Dataset:")
print(iris.shape)

# Column names

print("\nColumn Names:")
print(iris.columns)

# First 5 rows

print("\nFirst 5 Rows:")
print(iris.head())

# Dataset information

print("\nDataset Info:")
iris.info()

# Summary statistics

print("\nSummary Statistics:")
print(iris.describe())

# Scatter Plot

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=iris,
    x='sepal_length',
    y='petal_length',
    hue='species'
)

plt.title("Sepal Length vs Petal Length")
plt.show()

# Histograms

iris.hist(figsize=(10,8))

plt.suptitle("Feature Distributions")
plt.show()

# Boxplots

plt.figure(figsize=(12,6))

for i, column in enumerate(iris.columns[:-1]):
    plt.subplot(2,2,i+1)
    sns.boxplot(y=iris[column])
    plt.title(column)

plt.tight_layout()
plt.show()

"""Insights:

1. Iris dataset contains 150 rows and 5 columns.
2. Three flower species are present:
   - Setosa
   - Versicolor
   - Virginica
3. Petal measurements provide better separation between species.
4. Most features appear normally distributed.
5. Few potential outliers can be observed in boxplots.
"""